version: '3.4'
services:
  web:
    build: .
#    volumes:
#     - .:/usr/src/
    depends_on:
      - hub
    environment:
      DJANGO_TEST_PROCESSES: 1

    command: bash -c "
      dockerize -wait http://hub:4444  -timeout 20s
      && pytest
      "

  hub:
    image: vladislavzubov/selenium-standalone-chromium-pi
    restart: always
    container_name: selenium-chrome-standalone

    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
